/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siva
 */
public class ManageReservation extends javax.swing.JFrame {

    /**
     * Creates new form ManageReservation
     */
    RESERVE reserve=new RESERVE();
    public ManageReservation() {
        initComponents();
        reserve.fillTableReserve(tableReserve);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtReserveId = new javax.swing.JTextField();
        txtReserveClient = new javax.swing.JTextField();
        txtReserveRoom = new javax.swing.JTextField();
        btnReserveAdd = new javax.swing.JButton();
        btnReserveEdit = new javax.swing.JButton();
        btnReserveRemove = new javax.swing.JButton();
        btnReserveClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReserve = new javax.swing.JTable();
        btnReserveRefresh = new javax.swing.JButton();
        dateReserveIn = new com.toedter.calendar.JDateChooser();
        dateReserveOut = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel1.setText("Manage Reservations");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Client ID");

        jLabel4.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Room No");

        jLabel5.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date In");

        jLabel6.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date Out");

        txtReserveId.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N

        txtReserveClient.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N

        txtReserveRoom.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N

        btnReserveAdd.setFont(new java.awt.Font("Source Sans Pro", 1, 11)); // NOI18N
        btnReserveAdd.setText("Add");
        btnReserveAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveAddActionPerformed(evt);
            }
        });

        btnReserveEdit.setFont(new java.awt.Font("Source Sans Pro", 1, 11)); // NOI18N
        btnReserveEdit.setText("Edit");
        btnReserveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveEditActionPerformed(evt);
            }
        });

        btnReserveRemove.setFont(new java.awt.Font("Source Sans Pro", 1, 11)); // NOI18N
        btnReserveRemove.setText("Remove");
        btnReserveRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveRemoveActionPerformed(evt);
            }
        });

        btnReserveClear.setFont(new java.awt.Font("Source Sans Pro", 1, 11)); // NOI18N
        btnReserveClear.setText("Clear");
        btnReserveClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveClearActionPerformed(evt);
            }
        });

        tableReserve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Client Id", "Room No", "Date In", "Date Out"
            }
        ));
        tableReserve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableReserveMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableReserve);

        btnReserveRefresh.setText("Refresh");
        btnReserveRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveRefreshActionPerformed(evt);
            }
        });

        dateReserveIn.setDateFormatString("yyyy-MM-dd");
        dateReserveIn.setFont(new java.awt.Font("Source Sans Pro", 0, 11)); // NOI18N

        dateReserveOut.setDateFormatString("yyyy-MM-dd");
        dateReserveOut.setFont(new java.awt.Font("Source Sans Pro", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtReserveId, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txtReserveClient)
                            .addComponent(txtReserveRoom)
                            .addComponent(dateReserveIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateReserveOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnReserveAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReserveRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReserveClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReserveEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(btnReserveRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtReserveId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtReserveClient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtReserveRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dateReserveIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(dateReserveOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReserveAdd)
                            .addComponent(btnReserveEdit)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReserveRemove)
                    .addComponent(btnReserveClear)
                    .addComponent(btnReserveRefresh))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReserveAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveAddActionPerformed
        // TODO add your handling code here:
        try
        {
        String c,r;
        c=txtReserveClient.getText();
        r=txtReserveRoom.getText();
        int client=Integer.valueOf(txtReserveClient.getText());
        int room=Integer.valueOf(txtReserveRoom.getText());
        SimpleDateFormat sds=new SimpleDateFormat("yyyy-MM-dd");
        String in=sds.format(dateReserveIn.getDate());
        String out=sds.format(dateReserveOut.getDate());
        Date today=sds.parse(sds.format(new Date()));
        Date d_in=sds.parse(in);
        Date d_out=sds.parse(out);
        if(d_in.after(today)||d_in.equals(today))
        {
            if(!(d_out.before(d_in)))
            {
        if(in.equals("")||out.equals("")||r.trim().equals("")||c.trim().equals(""))
            JOptionPane.showMessageDialog(rootPane,"Please enter all values","Empty Fields",JOptionPane.WARNING_MESSAGE);
        else
        {
            if(reserve.addReserve(client,room,in,out))
                JOptionPane.showMessageDialog(rootPane,"Records added successfully","Add Reserve",JOptionPane.WARNING_MESSAGE);
            else
                JOptionPane.showMessageDialog(rootPane,"Records can't be added","Add Reserve Error",JOptionPane.WARNING_MESSAGE);
        }
        }
            else
                JOptionPane.showMessageDialog(rootPane,"Date out must be after Date in","Date Reserve Error",JOptionPane.WARNING_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(rootPane,"Date must be after or equal to 2day date","Date Reserve Error",JOptionPane.WARNING_MESSAGE);
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btnReserveAddActionPerformed

    private void tableReserveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReserveMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm=(DefaultTableModel)tableReserve.getModel();
        int rIndex=tableReserve.getSelectedRow();
        txtReserveId.setText(dtm.getValueAt(rIndex,0).toString());
        txtReserveClient.setText(dtm.getValueAt(rIndex,1).toString());
        txtReserveRoom.setText(dtm.getValueAt(rIndex,2).toString());
        dateReserveIn.setDate((Date)dtm.getValueAt(rIndex,3));
        dateReserveOut.setDate((Date)dtm.getValueAt(rIndex,4));
    }//GEN-LAST:event_tableReserveMouseClicked

    private void btnReserveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveEditActionPerformed
        // TODO add your handling code here:
        try
        {
        String c,r;
        c=txtReserveClient.getText();
        r=txtReserveRoom.getText();
        int id=Integer.valueOf(txtReserveId.getText());
        int client=Integer.valueOf(txtReserveClient.getText());
        int room=Integer.valueOf(txtReserveRoom.getText());
        SimpleDateFormat sds=new SimpleDateFormat("yyyy-MM-dd");
        String in=sds.format(dateReserveIn.getDate());
        String out=sds.format(dateReserveOut.getDate());
        Date today=sds.parse(sds.format(new Date()));
        Date d_in=sds.parse(in);
        Date d_out=sds.parse(out);
        if(d_in.after(today)||d_in.equals(today))
        {
            if(!(d_out.before(d_in)))
            {
        if(in.equals("")||out.equals("")||r.trim().equals("")||c.trim().equals(""))
            JOptionPane.showMessageDialog(rootPane,"Please enter all values","Empty Fields",JOptionPane.WARNING_MESSAGE);
        else
        {
            if(reserve.editReserve(id,client,room,in,out))
                JOptionPane.showMessageDialog(rootPane,"Records added successfully","Add Reserve",JOptionPane.WARNING_MESSAGE);
            else
                JOptionPane.showMessageDialog(rootPane,"Records can't be added","Add Reserve Error",JOptionPane.WARNING_MESSAGE);
        }
        }
            else
                JOptionPane.showMessageDialog(rootPane,"Date out must be after Date in","Date Reserve Error",JOptionPane.WARNING_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(rootPane,"Date must be after or equal to 2day date","Date Reserve Error",JOptionPane.WARNING_MESSAGE);
        }
        catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btnReserveEditActionPerformed

    private void btnReserveRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveRemoveActionPerformed
        // TODO add your handling code here:
                int id=Integer.valueOf(txtReserveId.getText());
                int room=Integer.valueOf(txtReserveRoom.getText());
            if(reserve.removeReserve(id,room))
            {
                JOptionPane.showMessageDialog(rootPane,"Records Deleted successfully","Delete Reserve",JOptionPane.WARNING_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane,"Records can't be deleted","Delete Reserve Error",JOptionPane.WARNING_MESSAGE);
            }
    }//GEN-LAST:event_btnReserveRemoveActionPerformed

    private void btnReserveClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveClearActionPerformed
        // TODO add your handling code here:
        txtReserveId.setText("");
        txtReserveClient.setText("");
        txtReserveRoom.setText("");
        dateReserveIn.setDate(null);
        dateReserveOut.setDate(null);
    }//GEN-LAST:event_btnReserveClearActionPerformed

    private void btnReserveRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveRefreshActionPerformed
        // TODO add your handling code here:
        tableReserve.setModel(new DefaultTableModel(null,new Object[]{"Id","Client Id","Room No","Date In","Date Out"}));
        reserve.fillTableReserve(tableReserve);
    }//GEN-LAST:event_btnReserveRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageReservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageReservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReserveAdd;
    private javax.swing.JButton btnReserveClear;
    private javax.swing.JButton btnReserveEdit;
    private javax.swing.JButton btnReserveRefresh;
    private javax.swing.JButton btnReserveRemove;
    private com.toedter.calendar.JDateChooser dateReserveIn;
    private com.toedter.calendar.JDateChooser dateReserveOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableReserve;
    private javax.swing.JTextField txtReserveClient;
    private javax.swing.JTextField txtReserveId;
    private javax.swing.JTextField txtReserveRoom;
    // End of variables declaration//GEN-END:variables
}
