/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siva
 */
public class ManageClient extends javax.swing.JFrame {

    /**
     * Creates new form ManageClient
     */
    CLIENT client=new CLIENT();
    public ManageClient() {
        initComponents();
        client.fillClientTable(tableClient);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtClientId = new javax.swing.JTextField();
        txtClientFname = new javax.swing.JTextField();
        txtClientLname = new javax.swing.JTextField();
        txtClientNo = new javax.swing.JTextField();
        txtClientMail = new javax.swing.JTextField();
        btnClientAdd = new javax.swing.JButton();
        btnClientEdit = new javax.swing.JButton();
        btnClientRemove = new javax.swing.JButton();
        btnClientClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClient = new javax.swing.JTable();
        btnClientRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel1.setText("Manage Clients");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(347, 347, 347))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phn No");

        jLabel6.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mail ID");

        txtClientId.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N

        txtClientFname.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N

        txtClientLname.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N

        txtClientNo.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N

        txtClientMail.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N

        btnClientAdd.setFont(new java.awt.Font("Source Sans Pro", 1, 11)); // NOI18N
        btnClientAdd.setText("Add");
        btnClientAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientAddActionPerformed(evt);
            }
        });

        btnClientEdit.setFont(new java.awt.Font("Source Sans Pro", 1, 11)); // NOI18N
        btnClientEdit.setText("Edit");
        btnClientEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientEditActionPerformed(evt);
            }
        });

        btnClientRemove.setFont(new java.awt.Font("Source Sans Pro", 1, 11)); // NOI18N
        btnClientRemove.setText("Remove");
        btnClientRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientRemoveActionPerformed(evt);
            }
        });

        btnClientClear.setFont(new java.awt.Font("Source Sans Pro", 1, 11)); // NOI18N
        btnClientClear.setText("Clear");
        btnClientClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientClearActionPerformed(evt);
            }
        });

        tableClient.setFont(new java.awt.Font("Source Sans Pro", 0, 11)); // NOI18N
        tableClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First Name", "Last Name", "Phn No", "Mail ID"
            }
        ));
        tableClient.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tableClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableClient);

        btnClientRefresh.setFont(new java.awt.Font("Source Sans Pro", 1, 11)); // NOI18N
        btnClientRefresh.setText("Refresh");
        btnClientRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtClientId, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(txtClientFname)
                            .addComponent(txtClientLname)
                            .addComponent(txtClientNo)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(53, 53, 53)
                            .addComponent(txtClientMail))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnClientRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClientAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(75, 75, 75)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnClientEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClientClear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClientRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtClientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtClientFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtClientLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtClientNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtClientMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClientAdd)
                            .addComponent(btnClientEdit)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientRemove)
                    .addComponent(btnClientClear)
                    .addComponent(btnClientRefresh))
                .addGap(0, 19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientAddActionPerformed
        // TODO add your handling code here:
        String fname=txtClientFname.getText();
        String lname=txtClientLname.getText();
        String no=txtClientNo.getText();
        String mail=txtClientMail.getText();
        if(fname.trim().equals("")||lname.trim().equals("")||no.trim().equals("")||mail.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane,"Please enter all the values","Empty Fields",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
        if(client.addClient(fname, lname, no, mail))
        {
            JOptionPane.showMessageDialog(rootPane,"New client added successfully","Add Client",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Sorry, records can't be added","Add Client Error",JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnClientAddActionPerformed

    private void btnClientClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientClearActionPerformed
        // TODO add your handling code here:
        txtClientId.setText("");
        txtClientFname.setText("");
        txtClientLname.setText("");
        txtClientNo.setText("");
        txtClientMail.setText("");
    }//GEN-LAST:event_btnClientClearActionPerformed

    private void tableClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm=(DefaultTableModel)tableClient.getModel();
        int rIndex=tableClient.getSelectedRow();
        txtClientId.setText(dtm.getValueAt(rIndex,0).toString());
        txtClientFname.setText(dtm.getValueAt(rIndex,1).toString());
        txtClientLname.setText(dtm.getValueAt(rIndex,2).toString());
        txtClientNo.setText(dtm.getValueAt(rIndex,3).toString());
        txtClientMail.setText(dtm.getValueAt(rIndex,4).toString());
    }//GEN-LAST:event_tableClientMouseClicked

    private void btnClientEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientEditActionPerformed
        // TODO add your handling code here:
        int id=Integer.valueOf(txtClientId.getText());
        String fname=txtClientFname.getText();
        String lname=txtClientLname.getText();
        String no=txtClientNo.getText();
        String mail=txtClientMail.getText();
        if(fname.trim().equals("")||lname.trim().equals("")||no.trim().equals("")||mail.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane,"Please enter all the values","Empty Fields",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
        if(client.editClient(id,fname,lname,no,mail))
            JOptionPane.showMessageDialog(rootPane,"Client details updated successfully","Edit Client",JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(rootPane,"Records can't be updated","Edit Client Error",JOptionPane.INFORMATION_MESSAGE);
        }
        txtClientId.setText("");
        txtClientFname.setText("");
        txtClientLname.setText("");
        txtClientNo.setText("");
        txtClientMail.setText("");
    }//GEN-LAST:event_btnClientEditActionPerformed

    private void btnClientRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientRemoveActionPerformed
        // TODO add your handling code here:
        int id=Integer.valueOf(txtClientId.getText());
        if(client.removeClient(id))
            JOptionPane.showMessageDialog(rootPane,"Client details deleted successfully","Delete Client",JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(rootPane,"Records can't be deleted","Delete Client Error",JOptionPane.INFORMATION_MESSAGE);
        txtClientId.setText("");
        txtClientFname.setText("");
        txtClientLname.setText("");
        txtClientNo.setText("");
        txtClientMail.setText("");
    }//GEN-LAST:event_btnClientRemoveActionPerformed

    private void btnClientRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientRefreshActionPerformed
        // TODO add your handling code here:
        tableClient.setModel(new DefaultTableModel(null,new Object[]{"ID","First Name","Last Name","Phn No","Mail ID"}));
        client.fillClientTable(tableClient);
    }//GEN-LAST:event_btnClientRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientAdd;
    private javax.swing.JButton btnClientClear;
    private javax.swing.JButton btnClientEdit;
    private javax.swing.JButton btnClientRefresh;
    private javax.swing.JButton btnClientRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableClient;
    private javax.swing.JTextField txtClientFname;
    private javax.swing.JTextField txtClientId;
    private javax.swing.JTextField txtClientLname;
    private javax.swing.JTextField txtClientMail;
    private javax.swing.JTextField txtClientNo;
    // End of variables declaration//GEN-END:variables
}
