/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagement;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Siva
 */
public class ManageRoom extends javax.swing.JFrame {

    /**
     * Creates new form ManageRoom
     */
    ROOMS rooms=new ROOMS();
    public ManageRoom() {
        initComponents();
        rooms.fillRoomTable(tableRoom);
        rooms.fillRoomCombo(comboRoomType);
        ButtonGroup bg=new ButtonGroup();
        bg.add(radioRoomYes);
        bg.add(radioRoomNo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtRoomNo = new javax.swing.JTextField();
        comboRoomType = new javax.swing.JComboBox<>();
        txtRoomPhn = new javax.swing.JTextField();
        btnRoomAdd = new javax.swing.JButton();
        btnRoomEdit = new javax.swing.JButton();
        btnRoomRemove = new javax.swing.JButton();
        btnRoomClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRoom = new javax.swing.JTable();
        btnRoomRefresh = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        radioRoomYes = new javax.swing.JRadioButton();
        radioRoomNo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro", 1, 18)); // NOI18N
        jLabel1.setText("Manage Rooms");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Number");

        jLabel3.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Type");

        jLabel4.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phn No");

        txtRoomNo.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        txtRoomNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRoomNoActionPerformed(evt);
            }
        });

        comboRoomType.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        comboRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRoomTypeActionPerformed(evt);
            }
        });

        txtRoomPhn.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N

        btnRoomAdd.setFont(new java.awt.Font("Source Sans Pro", 1, 11)); // NOI18N
        btnRoomAdd.setText("Add");
        btnRoomAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomAddActionPerformed(evt);
            }
        });

        btnRoomEdit.setFont(new java.awt.Font("Source Sans Pro", 1, 11)); // NOI18N
        btnRoomEdit.setText("Edit");
        btnRoomEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomEditActionPerformed(evt);
            }
        });

        btnRoomRemove.setFont(new java.awt.Font("Source Sans Pro", 1, 11)); // NOI18N
        btnRoomRemove.setText("Remove");
        btnRoomRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomRemoveActionPerformed(evt);
            }
        });

        btnRoomClear.setFont(new java.awt.Font("Source Sans Pro", 1, 11)); // NOI18N
        btnRoomClear.setText("Clear");
        btnRoomClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomClearActionPerformed(evt);
            }
        });

        tableRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number", "Type", "Phn No", "Reserved"
            }
        ));
        tableRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRoomMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRoom);

        btnRoomRefresh.setFont(new java.awt.Font("Source Sans Pro", 1, 11)); // NOI18N
        btnRoomRefresh.setText("Refresh");
        btnRoomRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomRefreshActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Source Sans Pro", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Reserved");

        radioRoomYes.setText("Yes");

        radioRoomNo.setText("No");
        radioRoomNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRoomNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRoomAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRoomRemove))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRoomEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRoomClear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radioRoomYes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(radioRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtRoomNo)
                                .addComponent(comboRoomType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRoomPhn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btnRoomRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboRoomType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtRoomPhn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(radioRoomYes)
                            .addComponent(radioRoomNo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRoomAdd)
                            .addComponent(btnRoomEdit)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRoomRemove)
                    .addComponent(btnRoomClear)
                    .addComponent(btnRoomRefresh))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRoomNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRoomNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRoomNoActionPerformed

    private void btnRoomRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomRefreshActionPerformed
        // TODO add your handling code here:
        tableRoom.setModel(new DefaultTableModel(null,new Object[]{"Number","Type","Phn No","Reserved"}));
        rooms.fillRoomTable(tableRoom);
    }//GEN-LAST:event_btnRoomRefreshActionPerformed

    private void comboRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRoomTypeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboRoomTypeActionPerformed

    private void btnRoomAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomAddActionPerformed
        // TODO add your handling code here:
        int number=Integer.valueOf(txtRoomNo.getText());
        int type=Integer.valueOf(comboRoomType.getSelectedItem().toString());
        String phn=txtRoomPhn.getText();
        String reserved="No";
        if(radioRoomYes.isSelected())
            reserved="Yes";
        if(txtRoomNo.getText().trim().equals("")||phn.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane,"Please enter all the values","Empty Fields",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
        if(rooms.addRoom(number, type, phn,reserved))
        {
            JOptionPane.showMessageDialog(rootPane,"New Room added successfully","Add Room",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Sorry, records can't be added","Add Room Error",JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnRoomAddActionPerformed

    private void btnRoomEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomEditActionPerformed
        // TODO add your handling code here:
        int number=Integer.valueOf(txtRoomNo.getText());
        int type=Integer.valueOf(comboRoomType.getSelectedItem().toString());
        String phn=txtRoomPhn.getText();
        String reserved="No";
        if(radioRoomYes.isSelected())
            reserved="Yes";
        if(txtRoomNo.getText().trim().equals("")||phn.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane,"Please enter all the values","Empty Fields",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
        if(rooms.editRoom(number, type, phn,reserved))
        {
            JOptionPane.showMessageDialog(rootPane,"Room records updated successfully","Edit Room",JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane,"Sorry, records can't be updated","Edit Room Error",JOptionPane.INFORMATION_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnRoomEditActionPerformed

    private void tableRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRoomMouseClicked
        // TODO add your handling code here:
         DefaultTableModel dtm=(DefaultTableModel)tableRoom.getModel();
        int rIndex=tableRoom.getSelectedRow();
        txtRoomNo.setText(dtm.getValueAt(rIndex,0).toString());
        comboRoomType.setSelectedItem(Integer.valueOf(dtm.getValueAt(rIndex,1).toString()));
        txtRoomPhn.setText(dtm.getValueAt(rIndex,2).toString());
        String s=dtm.getValueAt(rIndex, 3).toString();
        if(s.equals("Yes"))
        {
            radioRoomYes.setSelected(true);
        }
        else
        {
            radioRoomNo.setSelected(true);
        }
    }//GEN-LAST:event_tableRoomMouseClicked

    private void radioRoomNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRoomNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioRoomNoActionPerformed

    private void btnRoomRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomRemoveActionPerformed
        // TODO add your handling code here:
        int number=Integer.valueOf(txtRoomNo.getText());
        if(rooms.removeRoom(number))
            JOptionPane.showMessageDialog(rootPane,"Room details deleted successfully","Delete Room",JOptionPane.INFORMATION_MESSAGE);
        else
            JOptionPane.showMessageDialog(rootPane,"Records can't be deleted","Delete Room Error",JOptionPane.INFORMATION_MESSAGE);
        txtRoomNo.setText("");
        txtRoomPhn.setText("");
    }//GEN-LAST:event_btnRoomRemoveActionPerformed

    private void btnRoomClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomClearActionPerformed
        // TODO add your handling code here:
        txtRoomNo.setText("");
        txtRoomPhn.setText("");
        comboRoomType.setSelectedItem(1);
    }//GEN-LAST:event_btnRoomClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRoomAdd;
    private javax.swing.JButton btnRoomClear;
    private javax.swing.JButton btnRoomEdit;
    private javax.swing.JButton btnRoomRefresh;
    private javax.swing.JButton btnRoomRemove;
    private javax.swing.JComboBox<String> comboRoomType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioRoomNo;
    private javax.swing.JRadioButton radioRoomYes;
    private javax.swing.JTable tableRoom;
    private javax.swing.JTextField txtRoomNo;
    private javax.swing.JTextField txtRoomPhn;
    // End of variables declaration//GEN-END:variables
}
